# Action goal
nav_msgs/Path waypoints
bool use_timeout # will kill trajectory after certain time
duration timout # time to kill trajectory
bool avoid_obstacles
---
# Action result
bool success
bool killed
planning_ros_msgs/SplineTrajectory traj
---
# Action feedback
duration computation_time
float32 percent_to_kill
