# Goal
geometry_msgs/Pose p_init
geometry_msgs/Pose[] p_finals # a list of waypoints, if empty, will use single goal (i.e. p_final)
geometry_msgs/Pose p_final # the last waypoint,used to check whether the robot has finished all waypoints when replanning
float32 local_replan_rate
int16 global_replan_rate_factor
bool continue_mission # continue to finish waypoints in existing mission instead of starting a new mission
bool reset
bool avoid_obstacles
---
# Result
uint8 status
uint8 SUCCESS                      = 0
uint8 DYNAMICALLY_INFEASIBLE       = 1
uint8 NO_PATH                      = 2
uint8 CRITICAL_ERROR               = 3
uint8 IN_PROGRESS                  = 4
uint8 ABORT_FULL_MISSION           = 5
---
# Feedback
float64 distance_to_goal
int64 epoch
