# This should contain tracker parameters

#line_tracker_distance:
#  default_v_des: 2.5
#  default_a_des: 1.5
#  default_w_des: 2.5
#  epsilon: 0.1

#line_tracker_min_jerk:
#  default_v_des: 2.5
#  default_a_des: 1.5
#  default_yaw_v_des: 1.0
#  default_yaw_a_des: 0.5


take_off_tracker:
  thrust_rate: 5.0
  max_thrust: 4.0
  min_thurst: -9.8
  epsilon: 0.01

trajectory_tracker:
  max_pos_error: 2.0  # maximum tracker position error (in xy plane) allowed, default 1.0

trajectory_planner:
  debug: false # default false
  verbose: false # default false
  align_yaw: true # default false
  yaw_speed_magnitude: 0.3 # in rad
  use_lambda: true # pose error checking
  max_v: 2 # suggested for 2-D 9, for 3-D 3
  max_a: 2 # suggested for 2-D 7, for 3-D 2
  max_j: 1 # suggested for 2-D 3, for 3-D 2
  max_u: 1 # suggested for 2-D 3, for 3-D 1
  use_3d: false # use 3d planner
  z_cost_factor: 1 # global map z cost factor (cost_along_z = z_cost_factor * cost_along_x_or_y)
  max_v_z: 1.0 # default 2.0
  max_a_z: 2.0 # default 1.0
  max_j_z: 2.0 # default 1.0
  max_u_z: 1.0 # default 1.0
  tol_pos: 3.0 # distance tolerance for goal region, 0 means no tolerance, -1 means no limitation
  global_goal_tol_vel: 5.0 # tolerance of acceleration for goal region
  global_goal_tol_acc: -1 # tolerance of velocity for goal region
  dt: 1.0 # execution time for each primitive
  ndt: 1.0 # default 1
  max_num: -1 # Maxmum number of expansion, -1 means no limitation
  heuristic_weight: 5.0

stopping_policy:
  acc_xy_des: 4.0 #
  jerk_xy_des: 2.0 #
  acc_z_des: 2.0 #
  jerk_z_des: 1.0 #
  acc_yaw_des: 0.05 # rad

local_global_server:
  # local planning horizon will be from robot to the local voxel map boundary
  waypoint_reach_threshold: 10.0 # distance threshold, within which intermidiate waypoint is regarded as reached 
  final_goal_reach_threshold: 5.0 # within which final waypoint is regarded as reached, this should be smaller than waypoint_reach_threshold
  close_to_final_dist: 5 # distance-to-goal threshold, within which the velocity and acceleration checking will be turned on, -1 means no velocity checking at all
  local_plan_timeout_duration: 1.0 # local planner timeout in seconds 
  max_local_plan_trials: 3
  global_planner_verbose: false #
  odom_frame: "quadrotor/odom"
  map_frame: "quadrotor/map"
