uint8 status
uint8 RESET                    = 0
uint8 DONE                     = 1
uint8 LAST_GOAL_INFEASIBLE     = 2
uint8 LAST_GOAL_ACTIVE         = 3
geometry_msgs/Pose pos
bool stairs
---
geometry_msgs/Pose     goal
geometry_msgs/Pose[]     goals
bool       done_exploration
---
