Header header
uint64 time_of_week
uint16 year
uint8 month
uint8 day
uint8 hour
uint8 min
uint8 sec
uint8 valid
uint32 t_acc #ns 
int32 nano #ns 
uint8 fix_type
uint8 num_sat
int32 lon #deg *10^-7 
int32 lat #deg *10^-7 
int32 height #mm above elipsoid 
int32 height_msl #mm above mean sea level 
uint32 h_acc #mm 
uint32 v_acc #mm 
int32 vel_n #mm/s 
int32 vel_e #mm/s 
int32 vel_d #mm/s 
int32 g_speed #mm/s 
int32 head_mot #deg *10^-5 
uint32 s_acc #mm/s
uint32 head_acc #deg * 10^-5 
uint16 p_dop #*.01 
