imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.001
  accelerometer_random_walk: 0.0001
  gyroscope_noise_density: 0.0001
  gyroscope_random_walk: 1.0e-05
  model: calibrated
  rostopic: /ovc/vectornav/imu
  time_offset: 0.0
  update_rate: 400.0
