# Action goal
geometry_msgs/Pose p_init
geometry_msgs/Pose p_final
geometry_msgs/Twist v_init
geometry_msgs/Twist v_final
geometry_msgs/Twist a_init
geometry_msgs/Twist a_final
geometry_msgs/Twist j_init
geometry_msgs/Twist j_final
bool avoid_obstacles  # turns on collipsion avoidance
bool check_vel  # check velocity 
bool use_timeout # will kill trajectory after certain time
duration execution_time # time to execute trajectory
int64 epoch
float32 eval_time
planning_ros_msgs/SplineTrajectory last_traj
---
# Action result
bool success
bool killed
planning_ros_msgs/Path path
planning_ros_msgs/SplineTrajectory traj
geometry_msgs/Pose[] p_stop
geometry_msgs/Twist[] v_stop
geometry_msgs/Twist[] a_stop
geometry_msgs/Twist[] j_stop
geometry_msgs/Pose traj_end
duration execution_time # time to execute trajectory
int64 epoch
int64 policy_status
---
# Action feedback
duration computation_time
float32 percent_to_kill
bool jps_done #true when JPS finishes
bool decomp_done #true when decomposition done
bool optim_setup_done #true when everything except gurobi solve is done
