origin_x: -2
origin_y: -2
origin_z: 1 
range_x: 100
range_y: 85
range_z: 7
resolution: 0.5
max_range: 10.0
robot_r: 0.5 # map will be dilated in x and y directions for 2*[ceil(robot_r/res)] cells
robot_h: 0.5 # map will be dilated in z direction for 2*[ceil(robot_h/res)] cells (if robot_r is set as 0, there will not be any dilation along z either).

local:
  dim_x: 24.0
  dim_y: 24.0
  dim_z: 8.0
